version: 2.1

orbs:
 android: circleci/android@0.2.0
 
jobs:
  build:
    executor: android/android
#         /app/build/outputs/apk/deviceForTesters/release/app-deviceForTesters-release.apk
    steps:
      - checkout
      - run:
          name: apk check before
          command: |
             FILE=@app/app.iml
             if test -f "$FILE"; then
                echo "exists"
             else
                echo "dont"
             fi
      - run:
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - run:
          name: apk check after
          command: |
             FILE=@app/build/outputs/apk/deviceForTesters/release/app-deviceForTesters-release.apk
             if test -f "$FILE"; then
                echo "exists"
             else
                echo "dont"
             fi
