version: 2.1

orbs:
 android: circleci/android@0.2.0
 
jobs:
  build:
    executor: android/android
#         /app/build/outputs/apk/deviceForTesters/release/app-deviceForTesters-release.apk
    steps:
      - checkout
      - run:
          name: curl
          command: |
              curl --header "Authorization: token $githubtoken" --header "Accept: application/vnd.github.v3.raw" --remote-name --location "https://api.github.com/repos/machinne/test_key/contents/testcovid"
      - run:
          name: prepare
          command: |
              echo "circle_pass=$circle_pass" >> "./gradle.properties"
      - run:
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - run:
          command: |
            cd ./app/build/outputs/apk/deviceForTesters/release
            ls -l
